export const translations = {
    en: {
        Index: {
            dashboardTitle: "ECS",
            dashboardDescription: "Environmental Control System",
            sensorsSection: "Sensors",
            sensorsTitle: "Sensors",
            sensorsDescription: "Real-time sensor data",
            fanLightingControlSection: "Fan and Lighting Control",
            fanSpeedControlTitle: "Fan Speed Control",
            fanSpeedControlDescription: "Manually adjust fan speed",
            lightingControlTitle: "Lighting Control",
            lightingControlDescription: "Remotely control lights",
            aiOptimizationSection: "AI-Powered Optimization",
            aiOptimizationTitle: "AI-Powered Optimization",
            aiOptimizationDescription: "AI recommendation for optimal settings",
            cameraMonitoringSection: "Camera Monitoring",
            cameraMonitoringTitle: "Camera Monitoring",
            cameraMonitoringDescription: "Live camera feeds",
            historicalDataSection: "Historical Data Visualization",
            historicalDataTitle: "Historical Data Visualization",
            historicalDataDescription: "Visual representation of sensor data over time",
            managementIdeasTitle: "Management Ideas from AI",
            managementIdeasDescription: "AI analysis of sensor data for poultry farm management",
            aiSuggestion: "Based on historical data, AI suggests:",
            suggestion1: "Optimizing feeding schedules during peak temperature hours.",
            suggestion2: "Adjusting ventilation to maintain consistent humidity levels.",
            suggestion3: "Monitoring oxygen levels during nighttime to prevent hypoxia.",
            averageTemperature: "Average Temperature",
            averageHumidity: "Average Humidity",
            averageOxygen: "Average Oxygen",
            fanSpeedUpdatedTitle: "Fan speed updated.",
            fanSpeedUpdatedDescription: "Fan speed set to {speed}%.",
            lightStatusUpdatedTitle: "Light status updated.",
            lightStatusUpdatedDescription: "Lights {status}.",
            on: "turned on",
            off: "turned off",
            lightIntensity: "Light intensity",
            useCamera: "Use Camera:",
            cameraAccessRequired: "Camera Access Required",
            cameraAccessDescription: "Please allow camera access to use this feature.",
            cameraNumber: "Camera {number}",
            camera: "Camera" ,
            loadingRecommendation: "Loading AI recommendation...",
            currentSpeed: "Current speed",
            cameraAccessDeniedTitle: "Camera access denied",
            cameraAccessDeniedDescription: "Please enable camera access in your browser settings to use this feature."
        },
        Sensors: {
            temperatureTitle: "Temperature",
            temperatureDescription: "Current temperature in Celsius",
            humidityTitle: "Humidity",
            humidityDescription: "Current humidity percentage",
            oxygenTitle: "Oxygen",
            oxygenDescription: "Current oxygen level",
            lightIntensityTitle: "Light Intensity",
            lightIntensityDescription: "Current light intensity in Lux"
        },
        AI: {
            aiAssistant: "AI Assistant",
            aiDescription: "Ask questions and get AI-powered insights.",
            aiPlaceholder: "Ask any question about your farm data...",
            getAnswer: "Get Answer",
            loading: "Loading...",
            errorResponse: "Failed to get response from AI."
        }
    },
    fa: {
        Index: {
            dashboardTitle: "سیستم کنترل محیطی",
            dashboardDescription: "بررسی اجمالی داده‌های حسگر",
            sensorsSection: "حسگرها",
            sensorsTitle: "حسگرها",
            sensorsDescription: "داده‌های حسگر در زمان واقعی",
            fanLightingControlSection: "کنترل فن و روشنایی",
            fanSpeedControlTitle: "کنترل سرعت فن",
            fanSpeedControlDescription: "تنظیم دستی سرعت فن",
            lightingControlTitle: "کنترل روشنایی",
            lightingControlDescription: "کنترل از راه دور چراغ‌ها",
            aiOptimizationSection: "بهینه‌سازی مبتنی بر هوش مصنوعی",
            aiOptimizationTitle: "بهینه‌سازی مبتنی بر هوش مصنوعی",
            aiOptimizationDescription: "توصیه‌های هوش مصنوعی برای تنظیمات بهینه",
            cameraMonitoringSection: "نظارت دوربین",
            cameraMonitoringTitle: "نظارت دوربین",
            cameraMonitoringDescription: "فیدهای زنده دوربین",
            historicalDataSection: "نمایش داده‌های تاریخی",
            historicalDataTitle: "نمایش داده‌های تاریخی",
            historicalDataDescription: "نمایش بصری داده‌های حسگر در طول زمان",
            managementIdeasTitle: "ایده‌های مدیریتی از هوش مصنوعی",
            managementIdeasDescription: "تجزیه و تحلیل هوش مصنوعی داده‌های حسگر برای مدیریت مزرعه طیور",
            aiSuggestion: "بر اساس داده‌های تاریخی، هوش مصنوعی پیشنهاد می‌کند:",
            suggestion1: "بهینه‌سازی برنامه‌های غذایی در ساعات اوج دما.",
            suggestion2: "تنظیم تهویه برای حفظ سطوح رطوبت ثابت.",
            suggestion3: "نظارت بر سطوح اکسیژن در طول شب برای جلوگیری از هیپوکسی.",
            averageTemperature: "میانگین دما",
            averageHumidity: "میانگین رطوبت",
            averageOxygen: "میانگین اکسیژن",
            fanSpeedUpdatedTitle: "سرعت فن به‌روز شد.",
            fanSpeedUpdatedDescription: "سرعت فن روی {speed}% تنظیم شد.",
            lightStatusUpdatedTitle: "وضعیت چراغ به‌روز شد.",
            lightStatusUpdatedDescription: "چراغ‌ها {status}.",
            on: "روشن شدند",
            off: "خاموش شدند",
            lightIntensity: "شدت نور",
            useCamera: "استفاده از دوربین:",
            cameraAccessRequired: "دسترسی به دوربین مورد نیاز است",
            cameraAccessDescription: "لطفاً برای استفاده از این ویژگی، دسترسی به دوربین را مجاز کنید.",
            cameraNumber: "دوربین {number}",
            camera: "دوربین",
            loadingRecommendation: "در حال بارگیری توصیه هوش مصنوعی...",
            currentSpeed: "سرعت فعلی",
            cameraAccessDeniedTitle: "دسترسی به دوربین رد شد",
            cameraAccessDeniedDescription: "لطفاً برای استفاده از این ویژگی، دسترسی به دوربین را در تنظیمات مرورگر خود فعال کنید."
        },
        Sensors: {
            temperatureTitle: "دما",
            temperatureDescription: "دمای فعلی به سانتیگراد",
            humidityTitle: "رطوبت",
            humidityDescription: "درصد رطوبت فعلی",
            oxygenTitle: "اکسیژن",
            oxygenDescription: "سطح اکسیژن فعلی",
            lightIntensityTitle: "شدت نور",
            lightIntensityDescription: "شدت نور فعلی در لوکس"
        },
        AI: {
            aiAssistant: "دستیار هوش مصنوعی",
            aiDescription: "سوال بپرسید و از بینش‌های مبتنی بر هوش مصنوعی بهره‌مند شوید.",
            aiPlaceholder: "هر سوالی درباره داده‌های مزرعه خود بپرسید...",
            getAnswer: "دریافت پاسخ",
            loading: "در حال بارگذاری...",
            errorResponse: "دریافت پاسخ از هوش مصنوعی با خطا مواجه شد."
        }
    }
};
