import {ArrowRight, BarChart, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, LayoutDashboard, Lightbulb, Loader2, Mail, MessageSquare, Moon, PanelLeft, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Thermometer, Trash, User, Wind, X, Workflow} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  barChart: BarChart,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  lightbulb: Lightbulb,
  loader: Loader2,
  layoutDashboard: LayoutDashboard,
  mail: Mail,
  messageSquare: MessageSquare,
  panelLeft: PanelLeft,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  thermometer: Thermometer,
  trash: Trash,
  user: User,
  wind: Wind,
};

export {Icons};
